analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - lib/utils/csv_download_web.dart
include: package:flutter_lints/flutter.yaml
